# generated by scripts/gen_sdk.py — do not edit by hand
from .base import SturdyStatsBase


class ClfBase(SturdyStatsBase):
    """Classification is a two-stage process. First, pretrain a **clf-base** — a topic-aware base model trained over a committed dataset. Pretraining is computationally expensive and runs asynchronously. Once the clf-base is `ready`, train one or more **clf-models** on top of it: each clf-model learns to predict a set of label columns present in the training dataset. clf-models are designed for scalability and high-throughput inference, and require a minimum of 32 labeled examples per class. For few-shot or exploratory classification with less data, training a classifier via the index is more robust."""

    def list(self, transform = None):
        """
        List clf-bases
        
        Route: GET /classifiers/bases
        """
        _path = f"classifiers/bases"
        _resp = self._get(_path)
        import pandas as pd
        _df = pd.DataFrame(_resp['clf-bases'])
        return transform(_df) if transform else _df

    @classmethod
    def create(cls, dataset_id, model_name, org_id = None, api_key = None, base_url = None):
        """
        Pretrain a clf-base
        
        Route: POST /classifiers/bases
        
        Args:
            dataset_id — ID of the committed dataset to pretrain on.
            model_name — Human-readable name for this clf-base.
        """
        _path = f"classifiers/bases"
        _body = {k: v for k, v in {
            'dataset-id': dataset_id,
            'model-name': model_name,
        }.items() if v is not None}
        _inst = cls(org_id=org_id, api_key=api_key, base_url=base_url)
        _resp = _inst._post(_path, _body)
        _inst.id = _resp.get('clf-base-id')
        return _inst

    def status(self):
        """
        Get clf-base details
        
        Route: GET /classifiers/bases/{clf_base_id}
        """
        _path = f"classifiers/bases/{self.id}"
        return self._get(_path)

    def wait(self, poll_interval_start: float = 2.0, poll_interval_max: float = 60.0):
        """Block until entity reaches ready or failed state. Returns self.
        → GET classifiers/bases/{self.id}
        """
        import time
        from .base import SturdyStatsSdkError
        interval = poll_interval_start
        while True:
            _resp = self._get(f"classifiers/bases/{self.id}")
            _s = _resp.get('status')
            if _s == 'ready':
                return self
            if _s in {'failed'}:
                raise SturdyStatsSdkError(0, f"{self} failed with status '{_s}'")
            time.sleep(interval)
            interval = min(interval * 1.5, poll_interval_max)
