# generated by scripts/gen_sdk.py — do not edit by hand
from .base import SturdyStatsBase


class ClfBase(SturdyStatsBase):

    def list(self, transform = None):
        """
        List clf-bases
        → GET /classifiers/bases
        """
        _path = f"classifiers/bases"
        _resp = self._get(_path)
        import pandas as pd
        _df = pd.DataFrame(_resp['clf-bases'])
        return transform(_df) if transform else _df

    @classmethod
    def create(cls, dataset_id, model_name, org_id = None, api_key = None, base_url = None):
        """
        Pretrain a clf-base
        → POST /classifiers/bases
        """
        _path = f"classifiers/bases"
        _body = {k: v for k, v in {
            'dataset-id': dataset_id,
            'model-name': model_name,
        }.items() if v is not None}
        _inst = cls(org_id=org_id, api_key=api_key, base_url=base_url)
        _resp = _inst._post(_path, _body)
        _inst.id = _resp.get('clf-base-id')
        return _inst

    def status(self):
        """
        Get clf-base
        → GET /classifiers/bases/{clf_base_id}
        """
        _path = f"classifiers/bases/{self.id}"
        return self._get(_path)

    def wait(self, poll_interval_start: float = 2.0, poll_interval_max: float = 60.0):
        """Block until entity reaches ready or failed state. Returns self.
        → GET classifiers/bases/{self.id}
        """
        import time
        from .base import SturdyStatsSdkError
        interval = poll_interval_start
        while True:
            _resp = self._get(f"classifiers/bases/{self.id}")
            _s = _resp.get('status')
            if _s == 'ready':
                return self
            if _s in {'failed'}:
                raise SturdyStatsSdkError(0, f"{self} failed with status '{_s}'")
            time.sleep(interval)
            interval = min(interval * 1.5, poll_interval_max)
