# generated by scripts/gen_sdk.py — do not edit by hand
from __future__ import annotations
from typing import Any, Literal, Optional, TYPE_CHECKING, TypedDict
from .base import SturdyStatsBase

if TYPE_CHECKING:
    import pandas as pd


ClfBaseStatusResponse = TypedDict("ClfBaseStatusResponse", {
    'id': str,
    'name': str,
    'dataset': str,
    'status': str,
    'created-at': Optional[str],
    'ready-at': Optional[str],
    'details': Optional[Any],
})


class ClfBase(SturdyStatsBase):
    """Classification is a two-stage process. First, pretrain a **clf-base** — a topic-aware base model trained over a committed dataset. Pretraining is computationally expensive and runs asynchronously. Once the clf-base is `ready`, train one or more **clf-models** on top of it: each clf-model learns to predict a set of label columns present in the training dataset. clf-models are designed for scalability and high-throughput inference, and require a minimum of 32 labeled examples per class. For few-shot or exploratory classification with less data, training a classifier via the index is more robust."""

    def list(self, transform = None) -> "pd.DataFrame":
        """
        List clf-bases
        
        Route: GET /classifiers/bases
        
        Returns:
            pandas.DataFrame with columns:
                id (str): Clf-base identifier (m-<uuid>).
                name (str): Human-readable name.
                dataset (str): ID of the committed dataset this clf-base was pretrained on.
                status (str): Lifecycle status of the clf-base. Values: initializing (pretraining in progress), ready (available to build classifiers on), failed.
                created-at (Optional[str]): When pretraining was requested.
                ready-at (Optional[str]): When the clf-base became ready. Null if not yet complete.
        """
        _path = f"classifiers/bases"
        _resp = self._get(_path)
        import pandas as pd
        _df = pd.DataFrame(_resp['clf-bases'])
        return transform(_df) if transform else _df

    @classmethod
    def create(cls, dataset_id: str, model_name: str, org_id = None, api_key = None, base_url = None) -> "ClfBase":
        """
        Pretrain a clf-base
        
        Route: POST /classifiers/bases
        
        Args:
            dataset_id — ID of the committed dataset to pretrain on.
            model_name — Human-readable name for this clf-base.
        
        Returns:
            ClfBase instance (with .id set).
        """
        _path = f"classifiers/bases"
        _body = {k: v for k, v in {
            'dataset-id': dataset_id,
            'model-name': model_name,
        }.items() if v is not None}
        _inst = cls(org_id=org_id, api_key=api_key, base_url=base_url)
        _resp = _inst._post(_path, _body)
        _inst.id = _resp.get('clf-base-id')
        return _inst

    def status(self) -> ClfBaseStatusResponse:
        """
        Get clf-base details
        
        Route: GET /classifiers/bases/{clf_base_id}
        
        Returns:
            ClfBaseStatusResponse, a dict with:
                id (str): Clf-base identifier (m-<uuid>).
                name (str): Human-readable name.
                dataset (str): ID of the committed dataset this clf-base was pretrained on.
                status (str): Lifecycle status of the clf-base. Values: initializing (pretraining in progress), ready (available to build classifiers on), failed.
                created-at (Optional[str]): When pretraining was requested.
                ready-at (Optional[str]): When the clf-base became ready. Null if not yet complete.
                details (Optional[Any]): Job progress and metrics while training. Present on get, absent on list.
        """
        _path = f"classifiers/bases/{self.id}"
        return self._get(_path)

    def wait(self, poll_interval_start: float = 2.0, poll_interval_max: float = 60.0):
        """Block until entity reaches ready or failed state. Returns self.
        → GET classifiers/bases/{self.id}
        """
        import time
        from .base import SturdyStatsSdkError
        interval = poll_interval_start
        while True:
            _resp = self._get(f"classifiers/bases/{self.id}")
            _s = _resp.get('status')
            if _s == 'ready':
                return self
            if _s in {'failed'}:
                raise SturdyStatsSdkError(0, f"{self} failed with status '{_s}'")
            time.sleep(interval)
            interval = min(interval * 1.5, poll_interval_max)
