# generated by scripts/gen_sdk.py — do not edit by hand
from .base import SturdyStatsBase


class ClfModel(SturdyStatsBase):
    """Classification is a two-stage process. First, pretrain a **clf-base** — a topic-aware base model trained over a committed dataset. Pretraining is computationally expensive and runs asynchronously. Once the clf-base is `ready`, train one or more **clf-models** on top of it: each clf-model learns to predict a set of label columns present in the training dataset. clf-models are designed for scalability and high-throughput inference, and require a minimum of 32 labeled examples per class. For few-shot or exploratory classification with less data, training a classifier via the index is more robust."""

    def list(self, transform = None):
        """
        List clf-models
        
        Route: GET /classifiers/models
        """
        _path = f"classifiers/models"
        _resp = self._get(_path)
        import pandas as pd
        _df = pd.DataFrame(_resp['clf-models'])
        return transform(_df) if transform else _df

    @classmethod
    def create(cls, clf_base_id, dataset_id, model_name, fields, org_id = None, api_key = None, base_url = None):
        """
        Train a clf-model
        
        Route: POST /classifiers/models
        
        Args:
            clf_base_id — ID of the ready clf-base to fine-tune this classifier on top of.
            dataset_id — ID of the committed dataset containing the label columns to train on.
            model_name — Human-readable name for this clf-model.
            fields — The label column names from the training dataset that this classifier predicts. These must be columns present in the dataset used for training.
        """
        _path = f"classifiers/models"
        _body = {k: v for k, v in {
            'clf-base-id': clf_base_id,
            'dataset-id': dataset_id,
            'model-name': model_name,
            'fields': fields,
        }.items() if v is not None}
        _inst = cls(org_id=org_id, api_key=api_key, base_url=base_url)
        _resp = _inst._post(_path, _body)
        _inst.id = _resp.get('clf-model-id')
        return _inst

    def status(self):
        """
        Get clf-model details
        
        Route: GET /classifiers/models/{clf_model_id}
        """
        _path = f"classifiers/models/{self.id}"
        return self._get(_path)

    def predict_one(self, doc):
        """
        Classify
        
        Route: POST /classifiers/models/{clf_model_id}/predict/one
        
        Args:
            doc — The document text to classify.
        """
        _path = f"classifiers/models/{self.id}/predict/one"
        _body = {k: v for k, v in {
            'doc': doc,
        }.items() if v is not None}
        return self._post(_path, _body)

    def wait(self, poll_interval_start: float = 2.0, poll_interval_max: float = 60.0):
        """Block until entity reaches ready or failed state. Returns self.
        → GET classifiers/models/{self.id}
        """
        import time
        from .base import SturdyStatsSdkError
        interval = poll_interval_start
        while True:
            _resp = self._get(f"classifiers/models/{self.id}")
            _s = _resp.get('status')
            if _s == 'ready':
                return self
            if _s in {'failed'}:
                raise SturdyStatsSdkError(0, f"{self} failed with status '{_s}'")
            time.sleep(interval)
            interval = min(interval * 1.5, poll_interval_max)
