# generated by scripts/gen_sdk.py — do not edit by hand
from __future__ import annotations
from typing import Any, Literal, Optional, TYPE_CHECKING, TypedDict
from .base import SturdyStatsBase

if TYPE_CHECKING:
    import pandas as pd


ClfModelStatusResponse = TypedDict("ClfModelStatusResponse", {
    'id': str,
    'name': str,
    'clf-base': str,
    'dataset': str,
    'fields': list,
    'status': str,
    'created-at': Optional[str],
    'ready-at': Optional[str],
    'details': Optional[Any],
})

ClfModelPredictOneResponse = TypedDict("ClfModelPredictOneResponse", {
    'result': dict,
})


class ClfModel(SturdyStatsBase):
    """Classification is a two-stage process:
1. Pretrain a **clf-base** — a topic-aware base model trained over a committed dataset. Pretraining is computationally expensive and runs asynchronously.
2. Once the clf-base is `ready`, train one or more **clf-models** on top of it. Each clf-model learns to predict a set of label columns present in the training dataset.

clf-models are designed for scalability and high-throughput inference, and require a minimum of 32 labeled examples per class. For few-shot or exploratory classification with less data, training a classifier via the index is more robust."""

    def list(self, transform = None) -> "pd.DataFrame":
        """
        List all clf-models visible to the caller within this organisation.
        
        Route: GET /classifiers/models
        
        Returns:
            pandas.DataFrame with columns:
                id (str): Clf-model identifier (m-<uuid>).
                name (str): Human-readable name.
                clf-base (str): ID of the clf-base this model was fine-tuned from.
                dataset (str): ID of the dataset used for training.
                fields (list): The label column names from the training dataset that this classifier was trained to predict.
                status (str): Lifecycle status of the clf-model:
                    - initializing — training in progress
                    - ready — available for inference
                    - failed
                created-at (Optional[str]): When training was requested.
                ready-at (Optional[str]): When the clf-model became ready. Null if not yet complete.
        """
        _path = f"classifiers/models"
        _resp = self._get(_path)
        import pandas as pd
        _df = pd.DataFrame(_resp['clf-models'])
        return transform(_df) if transform else _df

    @classmethod
    def create(cls, clf_base_id: str, dataset_id: str, model_name: str, fields: list, org_id = None, api_key = None, base_url = None) -> "ClfModel":
        """
        Fine-tune a classifier on top of a ready clf-base using a committed dataset. Training runs asynchronously — poll /jobs/:id until status is succeeded. The clf-base must be ready, and the dataset must be committed. The fields specified must be column names present in the training dataset.
        
        Route: POST /classifiers/models
        
        Args:
            clf_base_id — ID of the ready clf-base to fine-tune this classifier on top of.
            dataset_id — ID of the committed dataset containing the label columns to train on.
            model_name — Human-readable name for this clf-model.
            fields — The label column names from the training dataset that this classifier predicts. These must be columns present in the dataset used for training.
        
        Returns:
            ClfModel instance (with .id set).
        """
        _path = f"classifiers/models"
        _body = {k: v for k, v in {
            'clf-base-id': clf_base_id,
            'dataset-id': dataset_id,
            'model-name': model_name,
            'fields': fields,
        }.items() if v is not None}
        _inst = cls(org_id=org_id, api_key=api_key, base_url=base_url)
        _resp = _inst._post(_path, _body)
        _inst.id = _resp.get('clf-model-id')
        return _inst

    def status(self) -> ClfModelStatusResponse:
        """
        Get a single clf-model's metadata by ID, including training status and job details.
        
        Route: GET /classifiers/models/{clf_model_id}
        
        Returns:
            ClfModelStatusResponse, a dict with:
                id (str): Clf-model identifier (m-<uuid>).
                name (str): Human-readable name.
                clf-base (str): ID of the clf-base this model was fine-tuned from.
                dataset (str): ID of the dataset used for training.
                fields (list): The label column names from the training dataset that this classifier was trained to predict.
                status (str): Lifecycle status of the clf-model:
                    - initializing — training in progress
                    - ready — available for inference
                    - failed
                created-at (Optional[str]): When training was requested.
                ready-at (Optional[str]): When the clf-model became ready. Null if not yet complete.
                details (Optional[Any]): Job progress and metrics while training. Present on get, absent on list.
        """
        _path = f"classifiers/models/{self.id}"
        return self._get(_path)

    def predict_one(self, doc: str) -> ClfModelPredictOneResponse:
        """
        Run inference on a single document using a ready clf-model. Returns a score for each label field the model was trained on.
        
        Route: POST /classifiers/models/{clf_model_id}/predict/one
        
        Args:
            doc — The document text to classify.
        
        Returns:
            ClfModelPredictOneResponse, a dict with:
                result (dict): Map of label name to predicted score for each field the model was trained on.
        """
        _path = f"classifiers/models/{self.id}/predict/one"
        _body = {k: v for k, v in {
            'doc': doc,
        }.items() if v is not None}
        return self._post(_path, _body)

    def wait(self, poll_interval_start: float = 2.0, poll_interval_max: float = 60.0):
        """Block until entity reaches ready or failed state. Returns self.
        → GET classifiers/models/{self.id}
        """
        import time
        from .base import SturdyStatsSdkError
        interval = poll_interval_start
        while True:
            _resp = self._get(f"classifiers/models/{self.id}")
            _s = _resp.get('status')
            if _s == 'ready':
                return self
            if _s in {'failed'}:
                raise SturdyStatsSdkError(0, f"{self} failed with status '{_s}'")
            time.sleep(interval)
            interval = min(interval * 1.5, poll_interval_max)
