# generated by scripts/gen_sdk.py — do not edit by hand
from .base import SturdyStatsBase


class Index(SturdyStatsBase):

    def list(self, transform = None):
        """
        List indices
        → GET /indices
        """
        _path = f"indices"
        _resp = self._get(_path)
        import pandas as pd
        _df = pd.DataFrame(_resp['indices'])
        return transform(_df) if transform else _df

    @classmethod
    def create(cls, name, dataset_id, private_annotations = False, model_arch = 'aalda-para', burn_in = 5000, sample = 150, n_topics = 192, training_overrides = None, org_id = None, api_key = None, base_url = None):
        """
        Create index and kick off training
        → POST /indices
        """
        _path = f"indices"
        _body = {k: v for k, v in {
            'name': name,
            'dataset-id': dataset_id,
            'private-annotations': private_annotations,
            'model-arch': model_arch,
            'burn-in': burn_in,
            'sample': sample,
            'n-topics': n_topics,
            'training-overrides': training_overrides,
        }.items() if v is not None}
        _inst = cls(org_id=org_id, api_key=api_key, base_url=base_url)
        _resp = _inst._post(_path, _body)
        _inst.id = _resp.get('index-id')
        return _inst

    def status(self):
        """
        Get index
        → GET /indices/{index_id}
        """
        _path = f"indices/{self.id}"
        return self._get(_path)

    def topics_search(self, level, filter = None, topic_mention_cutoff = 2.0, search_query = None, semantic_search_cutoff = 0.1, semantic_search_weight = 0.3, transform = None):
        """
        Topic inventory for a filtered set of units
        → POST /indices/{index_id}/topics/search
        """
        _path = f"indices/{self.id}/topics/search"
        _body = {k: v for k, v in {
            'level': level,
            'filter': filter,
            'topic-mention-cutoff': topic_mention_cutoff,
            'search-query': search_query,
            'semantic-search-cutoff': semantic_search_cutoff,
            'semantic-search-weight': semantic_search_weight,
        }.items() if v is not None}
        _resp = self._post(_path, _body)
        import pandas as pd
        _df = pd.DataFrame(_resp['topics'])
        return transform(_df) if transform else _df

    def topics_diff(self, level, filter1, filter2, topic_mention_cutoff = 2.0, prior_weight = 10.0, confidence_cutoff = 0.95, search_query1 = None, search_query2 = None, semantic_search_cutoff = 0.1, semantic_search_weight = 0.3, transform = None):
        """
        Bayesian topic diff between two filtered sets of units
        → POST /indices/{index_id}/topics/diff
        """
        _path = f"indices/{self.id}/topics/diff"
        _body = {k: v for k, v in {
            'level': level,
            'filter1': filter1,
            'filter2': filter2,
            'topic-mention-cutoff': topic_mention_cutoff,
            'prior-weight': prior_weight,
            'confidence-cutoff': confidence_cutoff,
            'search-query1': search_query1,
            'search-query2': search_query2,
            'semantic-search-cutoff': semantic_search_cutoff,
            'semantic-search-weight': semantic_search_weight,
        }.items() if v is not None}
        _resp = self._post(_path, _body)
        import pandas as pd
        _df = pd.DataFrame(_resp['topics'])
        return transform(_df) if transform else _df

    def search(self, level, search_query = None, filter = None, topic_ids = None, sort_by = 'relevance', topic_mention_cutoff = 2.0, semantic_search_cutoff = 0.1, semantic_search_weight = 0.3, limit = 20, transform = None):
        """
        Ranked unit retrieval with optional semantic search and topic filter
        → POST /indices/{index_id}/docs/search
        """
        _path = f"indices/{self.id}/docs/search"
        _body = {k: v for k, v in {
            'level': level,
            'search-query': search_query,
            'filter': filter,
            'topic-ids': topic_ids,
            'sort-by': sort_by,
            'topic-mention-cutoff': topic_mention_cutoff,
            'semantic-search-cutoff': semantic_search_cutoff,
            'semantic-search-weight': semantic_search_weight,
            'limit': limit,
        }.items() if v is not None}
        _resp = self._post(_path, _body)
        import pandas as pd
        _df = pd.DataFrame(_resp['results'])
        return transform(_df) if transform else _df

    def sql(self, sql, search_query = None, search_level = None, topic_mention_cutoff = 2.0, semantic_search_cutoff = 0.1, semantic_search_weight = 0.3, transform = None):
        """
        Run a SQL query against the index
        → POST /indices/{index_id}/sql
        """
        _path = f"indices/{self.id}/sql"
        _body = {k: v for k, v in {
            'sql': sql,
            'search-query': search_query,
            'search-level': search_level,
            'topic-mention-cutoff': topic_mention_cutoff,
            'semantic-search-cutoff': semantic_search_cutoff,
            'semantic-search-weight': semantic_search_weight,
        }.items() if v is not None}
        return self._load_parquet(_path, _body, transform=transform)

    def wait(self, poll_interval_start: float = 2.0, poll_interval_max: float = 60.0):
        """Block until entity reaches ready or failed state. Returns self.
        → GET indices/{self.id}
        """
        import time
        from .base import SturdyStatsSdkError
        interval = poll_interval_start
        while True:
            _resp = self._get(f"indices/{self.id}")
            _s = _resp.get('status')
            if _s == 'ready':
                return self
            if _s in {'failed'}:
                raise SturdyStatsSdkError(0, f"{self} failed with status '{_s}'")
            time.sleep(interval)
            interval = min(interval * 1.5, poll_interval_max)
