# generated by scripts/gen_sdk.py — do not edit by hand
from __future__ import annotations
from typing import Any, Literal, Optional, TYPE_CHECKING, TypedDict
from .base import SturdyStatsBase

if TYPE_CHECKING:
    import pandas as pd


IndexAppendResponse = TypedDict("IndexAppendResponse", {
    'index-id': str,
    'job-id': str,
    'dataset-id': str,
})

IndexStatusResponse = TypedDict("IndexStatusResponse", {
    'id': str,
    'name': str,
    'dataset': str,
    'status': str,
    'created-at': Optional[str],
    'ready-at': Optional[str],
    'details': Optional[Any],
})


class Index(SturdyStatsBase):
    """An index is a sparse topic model trained exclusively on a committed dataset. The model automatically infers interpretable topics and topic groups, then annotates every sentence, paragraph, and document with thematic content — storing the result as a structured, SQL-queryable data lake (DuckDB). Because the model uses joint probability rather than neural embeddings, the structure is explicit and inspectable: topics correspond to meaningful concepts, most values are zero, and every annotation can be traced back to specific passages.

Because topic annotations are stored as structured columns alongside any metadata you upload, you can jointly analyze thematic content and outcome metrics — surfacing which topics drive ratings, conversions, revenue, or any other signal you care about. This makes it possible not just to describe what your data is about, but to explain why metrics move.

Once `ready`, the index exposes five query endpoints that compose naturally:
- `topics/search` — topic inventory for a filtered unit set, with mention counts and prevalence. Use it to discover which topics exist and get their IDs.
- `topics/diff` — Bayesian comparison identifying topics significantly more prevalent in one segment than another.
- `topics/metric` — compares a per-document metric across topics between two segments, to surface which topics drive that metric.
- `docs/search` — retrieves and ranks units by a blend of exact-match + semantic search, topic filters, and SQL filters.
- `sql` — arbitrary DuckDB SQL against the entity views directly.

All endpoints operate at a configurable granularity level (`doc`, `paragraph`, `subparagraph`, or `sentence`), and all user-uploaded metadata columns are filter targets at every level. The endpoints share the same underlying views, so they are fully compatible: the same filters and search queries behave identically everywhere, and any high-level result can be unrolled to the underlying passages — the exact text behind any topic, segment, or metric is always retrievable via `docs/search` or `sql`."""

    def list(self, transform = None) -> "pd.DataFrame":
        """
        List all indices visible to the caller within this organisation.
        
        Route: GET /indices
        
        Returns:
            pandas.DataFrame with columns:
                id (str): Index identifier (ix-<uuid>).
                name (str): Human-readable name.
                dataset (str): ID of the dataset this index was built from.
                status (str): Lifecycle status:
                    - initializing — training in progress
                    - ready — available to query
                    - failed
                created-at (Optional[str]): When training was requested.
                ready-at (Optional[str]): When the index became ready. Null if not yet complete.
        """
        _path = f"indices"
        _resp = self._get(_path)
        import pandas as pd
        _df = pd.DataFrame(_resp['indices'])
        return transform(_df) if transform else _df

    @classmethod
    def create(cls, name: str, dataset_id: str, private_annotations: bool = False, model_arch: Literal['aalda', 'aalda-para', 'aalda-para-sent'] = 'aalda-para', burn_in: int = 5000, sample: int = 150, n_topics: int = 192, paragraph_delimiter: Literal['double-newline', 'single-newline', 'custom'] = 'double-newline', paragraph_delimiter_regex: Optional[str] = None, classification_fields: list = [], training_overrides: Optional[Any] = None, org_id = None, api_key = None, base_url = None) -> "Index":
        """
        Train a topic model index over a committed dataset. Training runs asynchronously — poll `/jobs/:id` until status is `succeeded`. The index must be ready before any query endpoints can be used.
        
        Route: POST /indices
        
        Args:
            name — Human-readable name for this index.
            dataset_id — ID of the committed dataset to build the index from. The dataset must be committed before training.
            private_annotations (default: False) — Reserved for future use.
            model_arch (default: 'aalda-para') — Topic model architecture to train:
                - "aalda": document-level topics. This is best for short documents such as tweets, text messsages, or abstracts. This model also provides the fastest training speed.
                - "aalda-para": paragraph-level topic model. This architecture is best for longer documents with short 'paragraph', such as phone call transcripts with alternating speakers or web content.
                - "aalda-para-sent": paragraph + sentence level topics: this model is best for long content with complex content in which a single paragraph may contain several complex ideas, such as financial documents, legal contracts, and earnings transcripts.

                The architecture does not affect the structure of the final output. All models will annotate and organize data into our standard document, paragraph, subparagraph, and sentence semantic units. The architecture simply provides additional structure to guide our models training process. More granular architectures enable flexibility and overdispersion for longer, more complex documents.
            burn_in (default: 5000) — Number of burn-in training iterations before sampling begins. Higher values improve topic quality at the cost of training time.
            sample (default: 150) — Number of posterior samples collected after burn-in. More samples give more stable topic estimates.
            n_topics (default: 192) — Upper bound on the number of topics to discover. Higher values produce finer-grained topics and increase training time linearly.
            paragraph_delimiter (default: 'double-newline') — How documents are split into paragraphs before tokenizing:
                - "double-newline": split on blank lines (one or more empty lines). This is the default and works well for prose.
                - "single-newline": split on every line break. Best when each line is its own unit, such as chat logs or line-delimited records.
                - "custom": split on the regular expression supplied in `paragraph-delimiter-regex`.

                This choice is frozen onto the index at train time and reused for every append, so all data in an index is segmented consistently.
            paragraph_delimiter_regex (default: None) — Custom paragraph-splitting regular expression. Required when `paragraph-delimiter` is "custom", and must be omitted otherwise.
            classification_fields (default: [])
            training_overrides (default: None) — Advanced training overrides. Leave nil unless instructed.
        
        Returns:
            Index instance (with .id set).
        """
        _path = f"indices"
        _body = {k: v for k, v in {
            'name': name,
            'dataset-id': dataset_id,
            'private-annotations': private_annotations,
            'model-arch': model_arch,
            'burn-in': burn_in,
            'sample': sample,
            'n-topics': n_topics,
            'paragraph-delimiter': paragraph_delimiter,
            'paragraph-delimiter-regex': paragraph_delimiter_regex,
            'classification-fields': classification_fields,
            'training-overrides': training_overrides,
        }.items() if v is not None}
        _inst = cls(org_id=org_id, api_key=api_key, base_url=base_url)
        _resp = _inst._post(_path, _body)
        _inst.id = _resp.get('index-id')
        return _inst

    def append(self, dataset_id: str) -> IndexAppendResponse:
        """
        Kick off prediction of a committed dataset against an existing index. Runs asynchronously — poll `/jobs/:id` until status is `succeeded`.
        
        Route: POST /indices/{index_id}/append
        
        Args:
            dataset_id — ID of the committed dataset to append to the index.
        
        Returns:
            IndexAppendResponse, a dict with:
                index-id (str):
                job-id (str):
                dataset-id (str):
        """
        _path = f"indices/{self.id}/append"
        _body = {k: v for k, v in {
            'dataset-id': dataset_id,
        }.items() if v is not None}
        return self._post(_path, _body)

    def status(self) -> IndexStatusResponse:
        """
        Get a single index's metadata by ID, including training status and job details.
        
        Route: GET /indices/{index_id}
        
        Returns:
            IndexStatusResponse, a dict with:
                id (str): Index identifier (ix-<uuid>).
                name (str): Human-readable name.
                dataset (str): ID of the dataset this index was built from.
                status (str): Lifecycle status:
                    - initializing — training in progress
                    - ready — available to query
                    - failed
                created-at (Optional[str]): When training was requested.
                ready-at (Optional[str]): When the index became ready. Null if not yet complete.
                details (Optional[Any]): Job progress and metrics while training. Present on get, absent on list.
        """
        _path = f"indices/{self.id}"
        return self._get(_path)

    def topics_search(self, level: Literal['doc', 'paragraph', 'subparagraph', 'sentence'], filter: Optional[str] = None, topic_mention_cutoff: float = 2.0, search_query: Optional[str] = None, semantic_search_cutoff: float = 0.1, semantic_search_weight: float = 0.3, transform = None) -> "pd.DataFrame":
        """
        Returns a high-level rollup of the topics present in any filtered subset of the index. Reports `mentions` (raw count of units containing the topic) and `prevalence` (fraction of the subset containing it). The `level` parameter sets the unit of measurement: at `level: "doc"`, 13 mentions means the topic occurred in 13 documents; at `level: "paragraph"`, 13 mentions means 13 paragraphs. A topic in 25 of 50 paragraphs has prevalence 0.5.

Use cases:
- Discover the topic inventory: run with no filter to see every topic the model found.
- Scope to a segment: `filter: "brand_name = 'Bosch'"` for what Bosch reviewers discuss.
- Combine with search: add `search-query` to roll up topics over just the semantically-relevant slice.

Example — topics in verified Bosch reviews mentioning noise:
```json
{"level": "doc",
 "filter": "brand_name = 'Bosch' AND verified_purchase = true",
 "search-query": "noise level during cycle"}
```
        
        Route: POST /indices/{index_id}/topics/search
        
        Args:
            level — Granularity level to operate at. Each level corresponds to a view over the index:
                - "doc": one row per document
                - "paragraph": one row per paragraph (adds paragraph_idx)
                - "subparagraph": one row per subparagraph (adds paragraph_idx, subparagraph_idx)
                - "sentence": one row per sentence (adds paragraph_idx, subparagraph_idx, sentence_idx)

                All levels expose: doc_id, text, topic_count MAP(SMALLINT, FLOAT),
                topic_prevalence MAP(SMALLINT, DOUBLE), semantic_topic_count MAP(VARCHAR, FLOAT),
                and all metadata columns from the original dataset (everything beyond the required
                doc_id and doc columns).
            filter (default: None) — Optional SQL WHERE clause (DuckDB syntax) applied against the entity view at the selected level.
                Available columns at all levels:
                - doc_id: document identifier
                - text (VARCHAR): text content at this granularity
                - topic_count (MAP(SMALLINT, FLOAT)): raw topic weight per topic_id
                - topic_prevalence (MAP(SMALLINT, DOUBLE)): topic weight normalised over all topics in this unit
                - semantic_topic_count (MAP(VARCHAR, FLOAT)): topic weight keyed by topic label string
                - All metadata columns from the original dataset (the columns you uploaded beyond doc_id/doc)
                Additional columns by level:
                - paragraph and above: paragraph_idx (USMALLINT)
                - subparagraph and above: subparagraph_idx (USMALLINT)
                - sentence: sentence_idx (USMALLINT)
                Example: "rating > 4 AND is_verified = true"
            topic_mention_cutoff (default: 2.0) — Minimum number of words attributed to a topic within a semantic unit for that unit to be considered as mentioning the topic. Higher values restrict to units where the topic is strongly present.
            search_query (default: None) — Natural language search query. Activates semantic search using the index topic model combined with exact match keyword matching. Results are ranked by a blended score controlled by semantic-search-weight; units below semantic-search-cutoff are excluded.
            semantic_search_cutoff (default: 0.1) — Minimum combined search score for a unit to appear in results when search-query is provided. Scores start near 0 (Hellinger distance scale); higher values restrict to closer matches.
            semantic_search_weight (default: 0.3) — Blend between IDF weighted exact match search and semantic (topic-based) search. 0.0 = pure keyword match, 1.0 = pure semantic similarity.
        
        Returns:
            pandas.DataFrame with columns:
                id (int): Integer topic ID. Use this to filter by topic in search and diff endpoints.
                label (str): Short descriptive label for the topic.
                group_label (str): Broader group label that this topic belongs to.
                mentions (int): Number of units in the filtered set that mention this topic (above topic-mention-cutoff).
                prevalence (float): Fraction of units in the filtered set that mention this topic.
        """
        _path = f"indices/{self.id}/topics/search"
        _body = {k: v for k, v in {
            'level': level,
            'filter': filter,
            'topic-mention-cutoff': topic_mention_cutoff,
            'search-query': search_query,
            'semantic-search-cutoff': semantic_search_cutoff,
            'semantic-search-weight': semantic_search_weight,
        }.items() if v is not None}
        _resp = self._post(_path, _body)
        import pandas as pd
        _df = pd.DataFrame(_resp['topics'])
        return transform(_df) if transform else _df

    def topics_diff(self, level: Literal['doc', 'paragraph', 'subparagraph', 'sentence'], test_subset: str, control_subset: str, topic_mention_cutoff: float = 2.0, prior_weight: float = 10.0, confidence_cutoff: float = 0.95, test_search_query: Optional[str] = None, control_search_query: Optional[str] = None, semantic_search_cutoff: float = 0.1, semantic_search_weight: float = 0.3, transform = None) -> "pd.DataFrame":
        """
        Compares topic prevalence between a test subset and a control subset (each a SQL filter) and returns topics significantly more prevalent in the test subset, via empirical Bayes beta-binomial statistics. `confidence` is the posterior probability that the topic's prevalence in the test subset exceeds the control subset; only topics above `confidence-cutoff` are returned, ordered by confidence descending. The two subsets are independent filters — to nest the test subset within the control subset, repeat the control's conditions in the test filter.

Use cases:
- Compare brands: `test-subset: "brand_name = 'Bosch'"` vs `control-subset: "brand_name = 'Miele'"` — what Bosch reviewers raise that Miele's don't.
- Compare within a brand: `test-subset: "brand_name = 'Bosch' AND product_name = 'Bosch 800 Series'"` vs `control-subset: "brand_name = 'Bosch'"` — what's distinctive about the 800 within the Bosch lineup.
- Outlier detection: low vs high ratings — `test-subset: "rating <= 2"` vs `control-subset: "rating >= 4"`.

Example — topics that distinguish 1–2 star Bosch reviews from 4–5 star Bosch reviews:
```json
{"level": "doc",
 "test-subset": "brand_name = 'Bosch' AND rating <= 2",
 "control-subset": "brand_name = 'Bosch' AND rating >= 4"}
```
        
        Route: POST /indices/{index_id}/topics/diff
        
        Args:
            level — Granularity level to operate at. Each level corresponds to a view over the index:
                - "doc": one row per document
                - "paragraph": one row per paragraph (adds paragraph_idx)
                - "subparagraph": one row per subparagraph (adds paragraph_idx, subparagraph_idx)
                - "sentence": one row per sentence (adds paragraph_idx, subparagraph_idx, sentence_idx)

                All levels expose: doc_id, text, topic_count MAP(SMALLINT, FLOAT),
                topic_prevalence MAP(SMALLINT, DOUBLE), semantic_topic_count MAP(VARCHAR, FLOAT),
                and all metadata columns from the original dataset (everything beyond the required
                doc_id and doc columns).
            test_subset — SQL WHERE clause defining the test subset — the group of interest checked for elevated topic prevalence.
                Available columns at all levels:
                - doc_id: document identifier
                - text (VARCHAR): text content at this granularity
                - topic_count (MAP(SMALLINT, FLOAT)): raw topic weight per topic_id
                - topic_prevalence (MAP(SMALLINT, DOUBLE)): topic weight normalised over all topics in this unit
                - semantic_topic_count (MAP(VARCHAR, FLOAT)): topic weight keyed by topic label string
                - All metadata columns from the original dataset (the columns you uploaded beyond doc_id/doc)
                Additional columns by level:
                - paragraph and above: paragraph_idx (USMALLINT)
                - subparagraph and above: subparagraph_idx (USMALLINT)
                - sentence: sentence_idx (USMALLINT)
            control_subset — SQL WHERE clause defining the control subset — the baseline the test subset's topic prevalence is compared against.
                Available columns at all levels:
                - doc_id: document identifier
                - text (VARCHAR): text content at this granularity
                - topic_count (MAP(SMALLINT, FLOAT)): raw topic weight per topic_id
                - topic_prevalence (MAP(SMALLINT, DOUBLE)): topic weight normalised over all topics in this unit
                - semantic_topic_count (MAP(VARCHAR, FLOAT)): topic weight keyed by topic label string
                - All metadata columns from the original dataset (the columns you uploaded beyond doc_id/doc)
                Additional columns by level:
                - paragraph and above: paragraph_idx (USMALLINT)
                - subparagraph and above: subparagraph_idx (USMALLINT)
                - sentence: sentence_idx (USMALLINT)
            topic_mention_cutoff (default: 2.0) — Minimum number of words attributed to a topic within a semantic unit for that unit to be considered as mentioning the topic. Higher values restrict to units where the topic is strongly present.
            prior_weight (default: 10.0) — Strength of the empirical Bayes prior when comparing topic prevalences. Higher values shrink estimates toward the global baseline, suppressing noise on low-mention topics.
            confidence_cutoff (default: 0.95) — Minimum posterior probability that topic prevalence in the test subset exceeds the control subset for a topic to be included in results.
            test_search_query (default: None) — Search query to further scope the test subset semantically.
            control_search_query (default: None) — Search query to further scope the control subset semantically.
            semantic_search_cutoff (default: 0.1) — Minimum combined search score for a unit to appear in results when search-query is provided. Scores start near 0 (Hellinger distance scale); higher values restrict to closer matches.
            semantic_search_weight (default: 0.3) — Blend between IDF weighted exact match search and semantic (topic-based) search. 0.0 = pure keyword match, 1.0 = pure semantic similarity.
        
        Returns:
            pandas.DataFrame with columns:
                id (int): Integer topic ID.
                label (str): Short descriptive label for the topic.
                group_label (str): Broader group label that this topic belongs to.
                confidence (float): Posterior probability (0–1) that this topic is more prevalent in the test subset than the control subset. Only topics above confidence-cutoff are returned.
                prevalence_ratio (float): Ratio of test-subset prevalence to control-subset prevalence.
                test_mentions (int): Number of units in the test subset that mention this topic.
                control_mentions (int): Number of units in the control subset that mention this topic.
                test_prevalence (float): Fraction of test-subset units mentioning this topic.
                control_prevalence (float): Fraction of control-subset units mentioning this topic.
                global_prevalence (float): Fraction of all units in the index mentioning this topic. Used as the empirical Bayes prior.
        """
        _path = f"indices/{self.id}/topics/diff"
        _body = {k: v for k, v in {
            'level': level,
            'test-subset': test_subset,
            'control-subset': control_subset,
            'topic-mention-cutoff': topic_mention_cutoff,
            'prior-weight': prior_weight,
            'confidence-cutoff': confidence_cutoff,
            'test-search-query': test_search_query,
            'control-search-query': control_search_query,
            'semantic-search-cutoff': semantic_search_cutoff,
            'semantic-search-weight': semantic_search_weight,
        }.items() if v is not None}
        _resp = self._post(_path, _body)
        import pandas as pd
        _df = pd.DataFrame(_resp['topics'])
        return transform(_df) if transform else _df

    def topics_metric(self, level: Literal['doc', 'paragraph', 'subparagraph', 'sentence'], test_metric: str, test_subset: Optional[str] = None, control_subset: Optional[str] = None, search_query: Optional[str] = None, topic_mention_cutoff: float = 2.0, prior_weight: float = 10.0, semantic_search_cutoff: float = 0.1, semantic_search_weight: float = 0.3, transform = None) -> "pd.DataFrame":
        """
        Compares a per-document metric across topics between two independent subsets of the index. For each topic, returns the metric averaged over the documents that mention it — denoised toward the control and whole-index baselines — so you can see which topics co-occur with higher or lower metric values.

Use cases:
- Explain a metric: `test-metric: "rating"` to see which topics co-occur with higher or lower star ratings.
- Compare a rate: `test-metric: "returned"` (booleans average as 0/1) to see which topics co-occur with higher return rates.
- Within a brand: `test-metric: "rating"`, `test-subset: "product_name = 'Bosch 800 Series'"` vs `control-subset: "brand_name = 'Bosch'"` — how the 800's per-topic ratings compare to the Bosch baseline.

Example — which topics are associated with lower ratings for Whirlpool:
```json
{"level": "doc",
 "test-metric": "rating",
 "test-subset": "brand_name = 'Whirlpool'"}
```
        
        Route: POST /indices/{index_id}/topics/metric
        
        Args:
            level — Granularity level to operate at. Each level corresponds to a view over the index:
                - "doc": one row per document
                - "paragraph": one row per paragraph (adds paragraph_idx)
                - "subparagraph": one row per subparagraph (adds paragraph_idx, subparagraph_idx)
                - "sentence": one row per sentence (adds paragraph_idx, subparagraph_idx, sentence_idx)

                All levels expose: doc_id, text, topic_count MAP(SMALLINT, FLOAT),
                topic_prevalence MAP(SMALLINT, DOUBLE), semantic_topic_count MAP(VARCHAR, FLOAT),
                and all metadata columns from the original dataset (everything beyond the required
                doc_id and doc columns).
            test_metric — SQL scalar expression over document-level metadata (DuckDB syntax), averaged over the
                distinct documents that mention each topic. Cast to DOUBLE automatically, so boolean
                rates work directly. Examples: "csat", "csat - 3", "refunded", "conversion = true".
                Must be a per-document value — only averaging is supported, not arbitrary aggregations.
                Documents where this expression is NULL are excluded from the whole analysis.
            test_subset (default: None) — Optional SQL WHERE clause (DuckDB syntax) defining the test subset — the group of interest whose per-topic metric you want to characterize. Defaults to the whole index, which yields index-wide per-topic metrics. May overlap or be disjoint from the control subset; the two are independent filters.
                Available columns at all levels:
                - doc_id: document identifier
                - text (VARCHAR): text content at this granularity
                - topic_count (MAP(SMALLINT, FLOAT)): raw topic weight per topic_id
                - topic_prevalence (MAP(SMALLINT, DOUBLE)): topic weight normalised over all topics in this unit
                - semantic_topic_count (MAP(VARCHAR, FLOAT)): topic weight keyed by topic label string
                - All metadata columns from the original dataset (the columns you uploaded beyond doc_id/doc)
                Additional columns by level:
                - paragraph and above: paragraph_idx (USMALLINT)
                - subparagraph and above: subparagraph_idx (USMALLINT)
                - sentence: sentence_idx (USMALLINT)
            control_subset (default: None) — Optional SQL WHERE clause (DuckDB syntax) defining the control subset — the baseline the test subset is compared against. Defaults to the whole index. Independent of the test subset (may overlap or be disjoint).
                Available columns at all levels:
                - doc_id: document identifier
                - text (VARCHAR): text content at this granularity
                - topic_count (MAP(SMALLINT, FLOAT)): raw topic weight per topic_id
                - topic_prevalence (MAP(SMALLINT, DOUBLE)): topic weight normalised over all topics in this unit
                - semantic_topic_count (MAP(VARCHAR, FLOAT)): topic weight keyed by topic label string
                - All metadata columns from the original dataset (the columns you uploaded beyond doc_id/doc)
                Additional columns by level:
                - paragraph and above: paragraph_idx (USMALLINT)
                - subparagraph and above: subparagraph_idx (USMALLINT)
                - sentence: sentence_idx (USMALLINT)
            search_query (default: None) — Optional natural language query that semantically scopes the whole analysis before SQL
                filtering. Applied to both the test and control subsets (an overall universe filter), so
                test and control are each intersected with the searched set. Activates the same blended
                keyword + semantic search as search-query.
            topic_mention_cutoff (default: 2.0) — Minimum number of words attributed to a topic within a semantic unit for that unit to be considered as mentioning the topic. Higher values restrict to units where the topic is strongly present.
            prior_weight (default: 10.0) — Strength of the empirical Bayes prior used to denoise the test subset's per-topic values.
                Test estimates shrink toward the control subset's per-topic estimates, which in turn shrink
                toward the whole-index per-topic baseline, each weighted by this many pseudo-observations.
                Higher values suppress noise on low-mention topics; 0 returns (very nearly) raw averages.
            semantic_search_cutoff (default: 0.1) — Minimum combined search score for a unit to appear in results when search-query is provided. Scores start near 0 (Hellinger distance scale); higher values restrict to closer matches.
            semantic_search_weight (default: 0.3) — Blend between IDF weighted exact match search and semantic (topic-based) search. 0.0 = pure keyword match, 1.0 = pure semantic similarity.
        
        Returns:
            pandas.DataFrame with columns:
                id (int): Integer topic ID.
                label (str): Short descriptive label for the topic.
                group_label (str): Broader group label that this topic belongs to.
                test_mentions_topic (int): Number of level-units in the test subset that mention this topic (above topic-mention-cutoff).
                control_mentions_topic (int): Number of level-units in the control subset that mention this topic (above topic-mention-cutoff). 0 if the topic is absent from the control subset.
                test_metric_topic (float): Denoised average of test-metric over distinct test-subset documents that mention this topic. Shrunk toward control_metric_topic by prior-weight.
                control_metric_topic (float): Denoised average of test-metric over distinct control-subset documents that mention this topic. Shrunk toward the whole-index per-topic average by prior-weight; the baseline test_metric_topic is compared against.
                test_metric_global (float): Average of test-metric over all distinct documents in the test subset (topic-agnostic).
                control_metric_global (float): Average of test-metric over all distinct documents in the control subset (topic-agnostic).
                test_prevalence_topic (float): Denoised fraction of test-subset level-units that mention this topic. Shrunk toward control_prevalence_topic by prior-weight.
                control_prevalence_topic (float): Denoised fraction of control-subset level-units that mention this topic. Shrunk toward the whole-index prevalence of this topic by prior-weight.
        """
        _path = f"indices/{self.id}/topics/metric"
        _body = {k: v for k, v in {
            'level': level,
            'test-metric': test_metric,
            'test-subset': test_subset,
            'control-subset': control_subset,
            'search-query': search_query,
            'topic-mention-cutoff': topic_mention_cutoff,
            'prior-weight': prior_weight,
            'semantic-search-cutoff': semantic_search_cutoff,
            'semantic-search-weight': semantic_search_weight,
        }.items() if v is not None}
        _resp = self._post(_path, _body)
        import pandas as pd
        _df = pd.DataFrame(_resp['topics'])
        return transform(_df) if transform else _df

    def search(self, level: Literal['doc', 'paragraph', 'subparagraph', 'sentence'], search_query: Optional[str] = None, filter: Optional[str] = None, topic_ids: Optional[list] = None, sort_by: str = 'relevance', topic_mention_cutoff: float = 2.0, semantic_search_cutoff: float = 0.1, semantic_search_weight: float = 0.3, limit: int = 20, transform = None) -> "pd.DataFrame":
        """
        Retrieve and rank units from the index at a given granularity level. Supports three independent signals that can be combined freely: a natural language search query (keyword + semantic), a list of topic IDs to filter and score by, and a SQL filter against any column in the entity view. Results include per-unit scores and aggregated topic info.

Use cases:
- Semantic retrieval: `search-query: "leaking from the door seal"` to find the actual complaints.
- Topic + segment drill-down: `topic-ids` from topics/search plus `filter: "brand_name = 'LG'"`.
- Pure SQL ranking: omit search and topics, and use `filter` with `sort-by`.

Example — LG paragraphs about door-seal leaks that mention topic 42:
```json
{"level": "paragraph",
 "search-query": "leaking from the door seal",
 "topic-ids": [42],
 "filter": "brand_name = 'LG'",
 "limit": 20}
```
        
        Route: POST /indices/{index_id}/docs/search
        
        Args:
            level — Granularity level to operate at. Each level corresponds to a view over the index:
                - "doc": one row per document
                - "paragraph": one row per paragraph (adds paragraph_idx)
                - "subparagraph": one row per subparagraph (adds paragraph_idx, subparagraph_idx)
                - "sentence": one row per sentence (adds paragraph_idx, subparagraph_idx, sentence_idx)

                All levels expose: doc_id, text, topic_count MAP(SMALLINT, FLOAT),
                topic_prevalence MAP(SMALLINT, DOUBLE), semantic_topic_count MAP(VARCHAR, FLOAT),
                and all metadata columns from the original dataset (everything beyond the required
                doc_id and doc columns).
            search_query (default: None) — Natural language search query. Activates semantic search using the index topic model combined with exact match keyword matching. Results are ranked by a blended score controlled by semantic-search-weight; units below semantic-search-cutoff are excluded.
            filter (default: None) — Optional SQL WHERE clause (DuckDB syntax) applied against the entity view at the selected level.
                Available columns at all levels:
                - doc_id: document identifier
                - text (VARCHAR): text content at this granularity
                - topic_count (MAP(SMALLINT, FLOAT)): raw topic weight per topic_id
                - topic_prevalence (MAP(SMALLINT, DOUBLE)): topic weight normalised over all topics in this unit
                - semantic_topic_count (MAP(VARCHAR, FLOAT)): topic weight keyed by topic label string
                - All metadata columns from the original dataset (the columns you uploaded beyond doc_id/doc)
                Additional columns by level:
                - paragraph and above: paragraph_idx (USMALLINT)
                - subparagraph and above: subparagraph_idx (USMALLINT)
                - sentence: sentence_idx (USMALLINT)
                Example: "rating > 4 AND is_verified = true"
            topic_ids (default: None) — Filter results to units that mention these topic IDs (integer IDs from the topics/search endpoint). Units are ranked by their combined score for these topics.
            sort_by (default: 'relevance') — SQL expression for ORDER BY DESC. The special value "relevance" auto-selects: search_score * topic_score (both), search_score (search only), topic_score (topics only), doc_id (neither).
            topic_mention_cutoff (default: 2.0) — Minimum number of words attributed to a topic within a semantic unit for that unit to be considered as mentioning the topic. Higher values restrict to units where the topic is strongly present.
            semantic_search_cutoff (default: 0.1) — Minimum combined search score for a unit to appear in results when search-query is provided. Scores start near 0 (Hellinger distance scale); higher values restrict to closer matches.
            semantic_search_weight (default: 0.3) — Blend between IDF weighted exact match search and semantic (topic-based) search. 0.0 = pure keyword match, 1.0 = pure semantic similarity.
            limit (default: 20) — Maximum number of results to return.
        
        Returns:
            pandas.DataFrame with columns:
                doc_id (str): Document identifier.
                paragraph_idx (Optional[int]): Paragraph index within the document. Null at doc level.
                subparagraph_idx (Optional[int]): Sub-paragraph index within the paragraph. Null at doc and paragraph levels.
                sentence_idx (Optional[int]): Sentence index within the sub-paragraph. Null above sentence level.
                text (str): Text content of this unit at the requested granularity level.
                scores (dict): Relevance scores for this result.
                topics (list): Topics associated with this unit (above topic-mention-cutoff), ordered by topic_id.
        """
        _path = f"indices/{self.id}/docs/search"
        _body = {k: v for k, v in {
            'level': level,
            'search-query': search_query,
            'filter': filter,
            'topic-ids': topic_ids,
            'sort-by': sort_by,
            'topic-mention-cutoff': topic_mention_cutoff,
            'semantic-search-cutoff': semantic_search_cutoff,
            'semantic-search-weight': semantic_search_weight,
            'limit': limit,
        }.items() if v is not None}
        _resp = self._post(_path, _body)
        import pandas as pd
        _df = pd.DataFrame(_resp['results'])
        return transform(_df) if transform else _df

    def sql(self, sql: str, search_query: Optional[str] = None, search_level: Optional[Literal['doc', 'paragraph', 'subparagraph', 'sentence']] = None, topic_mention_cutoff: float = 2.0, semantic_search_cutoff: float = 0.1, semantic_search_weight: float = 0.3, transform = None) -> "pd.DataFrame":
        """
        Execute arbitrary SQL against the index entity views. Returns results as a parquet file. This is the full-flexibility escape hatch — anything expressible in SQL works here, including aggregations, joins to the topics table, and window functions. See the `sql` field description for the full view schema. The parquet response is capped at 25 MB; larger results return 413 — narrow the query or page with LIMIT/OFFSET (with an ORDER BY).
        
        Route: POST /indices/{index_id}/sql
        
        Args:
            sql — SQL SELECT statement (DuckDB syntax) to run against the index. Returns results as a parquet file (application/vnd.apache.parquet).

                Available views:
                - doc, paragraph, subparagraph, sentence — entity views at each granularity level.
                All views expose: doc_id, text (VARCHAR), topic_count MAP(SMALLINT, FLOAT),
                topic_prevalence MAP(SMALLINT, DOUBLE), semantic_topic_count MAP(VARCHAR, FLOAT),
                plus all metadata columns from the original dataset (beyond the required doc_id/doc columns).
                Finer levels add: paragraph_idx (USMALLINT), subparagraph_idx (USMALLINT), sentence_idx (USMALLINT).
                - topics — global topic reference table: id (SMALLINT), group_id (SMALLINT),
                label (VARCHAR), group_label (VARCHAR), c (BIGINT total count)

                The query must be in the form of a single SELECT statement. CTEs are allowed. For descriptive queries such as DESCRIBE TABLE or SHOW ALL TABLES must be wrapped eg SELECT * FROM (DESCRIBE TABLE doc) statement.

                There are also several lower level relations which can be helpful for more advanced queries, such as tokens, doc_meta, doc_topics, paragraph_topics, subparagraph_topics, and sentence_topics.

                When a search query is provided, the doc, paragraph, subparagraph, and sentence tables are filtered by the most restrictive possible criteria. E.g. if the search_level is 'doc', each table is filtered to only include doc_ids that pass the semantic search filter. If the search level is sentence, paragraphs are filtered to only paragraph that contain sentences that pass the semantic search filter. The resulting tables are unordered.

                We expose the underlying search scores in a 'search_scores' table that contains the topic_search_score, exact_match_score, and the combined search_score. We expose the processed search_query under the database namespace `search_query.main`. This database namespace contains all the same tables as the main namespace, scoped only to the provided search query. This underlying data provides a powerful set of options for advanced retrieval use-cases.
            search_query (default: None) — Natural language search query. Activates semantic search using the index topic model combined with exact match keyword matching. Results are ranked by a blended score controlled by semantic-search-weight; units below semantic-search-cutoff are excluded.
            search_level (default: None) — Granularity level to use for search setup when search-query is provided. Required if search-query is set.
            topic_mention_cutoff (default: 2.0) — Minimum number of words attributed to a topic within a semantic unit for that unit to be considered as mentioning the topic. Higher values restrict to units where the topic is strongly present.
            semantic_search_cutoff (default: 0.1) — Minimum combined search score for a unit to appear in results when search-query is provided. Scores start near 0 (Hellinger distance scale); higher values restrict to closer matches.
            semantic_search_weight (default: 0.3) — Blend between IDF weighted exact match search and semantic (topic-based) search. 0.0 = pure keyword match, 1.0 = pure semantic similarity.
        
        Returns:
            pandas.DataFrame of the query result.
        """
        _path = f"indices/{self.id}/sql"
        _body = {k: v for k, v in {
            'sql': sql,
            'search-query': search_query,
            'search-level': search_level,
            'topic-mention-cutoff': topic_mention_cutoff,
            'semantic-search-cutoff': semantic_search_cutoff,
            'semantic-search-weight': semantic_search_weight,
        }.items() if v is not None}
        return self._load_parquet(_path, _body, transform=transform)

    def wait(self, poll_interval_start: float = 2.0, poll_interval_max: float = 60.0):
        """Block until entity reaches ready or failed state. Returns self.
        → GET indices/{self.id}
        """
        import time
        from .base import SturdyStatsSdkError
        interval = poll_interval_start
        while True:
            _resp = self._get(f"indices/{self.id}")
            _s = _resp.get('status')
            if _s == 'ready':
                return self
            if _s in {'failed'}:
                raise SturdyStatsSdkError(0, f"{self} failed with status '{_s}'")
            time.sleep(interval)
            interval = min(interval * 1.5, poll_interval_max)
